# Generated by Django 3.1.1 on 2021-06-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('title', models.CharField(max_length=70)),
                ('title_en', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.FileField(upload_to='static/images')),
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('title', models.CharField(max_length=70)),
                ('title_en', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('description_en', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ordering', models.IntegerField()),
                ('image', models.FileField(upload_to='static/images')),
                ('icon', models.FileField(upload_to='static/icons')),
                ('id_field', models.AutoField(primary_key=True, serialize=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Place', to='beotura.tour')),
            ],
        ),
    ]
